boutique_homepage:
    path:     /index
    defaults: { _controller: BoutiqueBundle:Default:index }

demande:
    path:     /demande
    defaults: { _controller: FOSUserBundle:Registration:register }
    methods:  [GET, POST]

registerclt:
    path:     /{username}.com/registerclt
    defaults: { _controller: FOSUserBundle:Registration:firstregisterclt }
    methods:  [GET, POST]

login:
    path:      /{username}.com/login
    defaults: { _controller: FOSUserBundle:Security:login }

preloginBoutique:
    path:     /SaisieNomBoutique
    defaults: { _controller: BoutiqueBundle:Default:SaisieNomBoutique }
    methods:  [GET, POST]

logout:
    path:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

login_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    methods:  POST

backend:
    resource: "@BoutiqueBundle/Resources/config/routing/backend.yml"
    prefix:   /{username}.com/admin

fontend:
    resource: "@BoutiqueBundle/Resources/config/routing/frontend.yml"
    prefix:   /{username}.com

cltloggedin:
    resource: "@BoutiqueBundle/Resources/config/routing/clt.yml"
    prefix: /{nomB}.com/{cltname}

compte_clt:
    path:     /{nomB}.com/{cltname}/mon_compte
    defaults: { _controller: BoutiqueBundle:Client:compteclt }
    methods:  [GET, POST]

check_clt:
    path:     /{nomB}.com/check/{cltname}
    defaults: { _controller: BoutiqueBundle:Default:checkclt }
    methods:  [GET, POST]

