user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

boutique:
    resource: "@BoutiqueBundle/Resources/config/routing.yml"
    prefix:   /BoutiqueService

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"