<?php

namespace BoutiqueBundle\Repository;

/**
 * Categorie_BoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie_BoutiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
