<?php

namespace BoutiqueBundle\Repository;

/**
 * FiltreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiltreRepository extends \Doctrine\ORM\EntityRepository
{
}
