<?php

namespace BoutiqueBundle\Repository;

/**
 * Marque_BoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Marque_BoutiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
