<?php

namespace BoutiqueBundle\Repository;

/**
 * Produit_CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit_CommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
