<?php

namespace BoutiqueBundle\Repository;

/**
 * ProduitcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitcRepository extends \Doctrine\ORM\EntityRepository
{
}
